### ISSUE TITLE
vitejs + vue + typescript 

### ISSUE THREAD

**Issue by skisensations** [higuaifan/rollup-plugin-fontmin#1]
Dear [higuaifan](https://github.com/higuaifan),
First thank you for your shared work.
I recently move from vue-cli to vite and I need to minify my fonts. I saw your rollup plugin and try it.

``` javascript
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import RollupPluginFontmin from '@higuaifan/rollup-plugin-fontmin'

export default defineConfig({
  plugins: [vue(),
  RollupPluginFontmin({
    fontSrc: 'dist/assets/*.ttf',
    fontDest: 'dist/assets',
  })]
})
```
But I always get the same error that RollupPluginFontmin is not a function even if I saw that it is a function !
```bash
failed to load config from /tmp/path/vite.config.js
error when starting dev server:
TypeError: RollupPluginFontmin is not a function
    at file:///tmp/path/vite.config.js.timestamp-1662032643422.mjs:8:5
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async loadConfigFromBundledFile (file:///tmp/path/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:63077:21)
    at async loadConfigFromFile (file:///tmp/path/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:62963:28)
    at async resolveConfig (file:///tmp/path/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:62577:28)
    at async createServer (file:///tmp/path/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:59183:20)
    at async CAC.<anonymous> (file:///tmp/path/node_modules/vite/dist/node/cli.js:699:24)
```

You can check my test repo (branch RollupPluginFontmin) at https://github.com/lesailesdumontblanc-com/lesailesdumontblanc/tree/RollupPluginFontmin

**Comment by higuaifan** [comment]
Thanks for your use and issue!
----
Looks like in `.js` type vite config can not import default function,
I will fix this if I can. Might take some times.
I this version, you can try this:
``` js
export default defineConfig({
  plugins: [vue(),
  RollupPluginFontmin.default({
    fontSrc: 'dist/assets/*.ttf',
    fontDest: 'dist/assets',
  })]
})
```

**Comment by eltorio** [comment]
Thank you higuaifan,
my solution is in vite.config.ts :
```javascript
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { default as _RollupPluginFontmin, OptionType } from '@higuaifan/rollup-plugin-fontmin'
import { Plugin } from "rollup";

declare type RollupPluginFontminType = (pluginOption?: OptionType) => Plugin;
const RollupPluginFontmin = ((_RollupPluginFontmin as any).default) as RollupPluginFontminType

export default defineConfig({
  plugins: [vue(),
  RollupPluginFontmin({
    fontSrc: 'dist/assets/*.ttf',
    fontDest: 'dist/assets',
    fileExt: ['ts', 'vue', 'js'],
    include: 'src/**/*'
  })]
})

```

**Comment by higuaifan** [comment]
> Thank you higuaifan, my solution is in vite.config.ts :
> 
> ```js
> import { defineConfig } from 'vite'
> import vue from '@vitejs/plugin-vue'
> import { default as _RollupPluginFontmin, OptionType } from '@higuaifan/rollup-plugin-fontmin'
> import { Plugin } from "rollup";
> 
> declare type RollupPluginFontminType = (pluginOption?: OptionType) => Plugin;
> const RollupPluginFontmin = ((_RollupPluginFontmin as any).default) as RollupPluginFontminType
> 
> export default defineConfig({
>   plugins: [vue(),
>   RollupPluginFontmin({
>     fontSrc: 'dist/assets/*.ttf',
>     fontDest: 'dist/assets',
>     fileExt: ['ts', 'vue', 'js'],
>     include: 'src/**/*'
>   })]
> })
> ```

😂I think the code for `plugin` is a bit too much, this plugin not worth it.
I found because of `type:'module'` in `package.json`, even  in `vite.config.ts` still can not found `RollupPluginFontmin`
I plan to release a new version, make `RollupPluginFontmin ` not default.
vue3 suggest avoid export default too.
